# see https://jupyterbook.org/customize/config.html
title: Pywavelet.case_studies.gaps
author: pywavelet developers

execute:
  execute_notebooks: 'off'


repository:
  url: https://github.com/pywavelet/case_studies.gaps
  path_to_book: docs
  branch: main

html:
  use_issues_button: true
  use_repository_button: true


sphinx:
  extra_extensions:
    - sphinx.ext.autodoc
