name: Python Package Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: python -m pip install -e .[dev]

      - name: pytest
        run: |  
          cd examples/Noise/Gaps
          pytest --cov='gap_study_utils' --cov-report term-missing

      - name: Upload Coverage to Coveralls
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          cd examples/Noise/Gaps
          coverage xml
          pip install coveralls
          coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
